### ISSUE TITLE
Selecting a line (or part thereof) will cause the entire contents of the chatbox above it to be selected

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#55]
This occurs on refresh of the chat box; when selecting part of or all of a line, the entire contents of the box before the selected area will also be selected.  This is most likely a function of the refresh.

**Comment by EnzoMartin** [comment]
Well, there's a bigger issue with that because the way it's done, since it always return a chunk of messages, we replace the entire contents, so if you try to select, and it updates, it'll kill your selection.

I think a better solution would be to change how the server returns messages and append new messages, so it only sends new messages and not past ones
